Update semgrep.yml

diff --git a/.github/workflows/semgrep.yml b/.github/workflows/semgrep.yml
--- a/.github/workflows/semgrep.yml
+++ b/.github/workflows/semgrep.yml
@@ -21,4 +21,26 @@ jobs:
       image: returntocorp/semgrep
     steps:
     - uses: actions/checkout@v3
-    - run: semgrep ci
+    - name: Run script on push
+      if: github.event_name == 'push'
+      run: semgrep ci 
+
+    - name: Run script on pull request
+      if: github.event_name == 'pull_request'
+    - run: |
+        echo "Running semgrep and dumping results to JSON file"
+        semgrep ci --json --output report.json || true
+        json_file=report.json
+        echo "Iterating through findings"
+        findings=$(jq -r '.results[]' "$json_file")
+        for k in $(jq '.results | keys | .[]' "$json_file"); do
+            value=$(jq -r ".results[$k]" "$json_file");
+            echo "$value" > finding_content.json
+            severity=$(jq -r '.extra.severity' "finding_content.json");
+            confidence=$(jq -r '.extra.metadata.confidence' "finding_content.json");
+            if [[ $severity == "ERROR" && $confidence == "HIGH" ]]; then
+                echo "Exiting with error code 1"
+                exit 1;
+            fi
+        done
+        echo "There are no critical-high findings"
